"""test running migrations

Revision ID: 0086892c604f
Revises: 323921059531
Create Date: 2023-06-28 16:39:49.814606

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0086892c604f'
down_revision = '323921059531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
