"""test running migrations

Revision ID: 00995c1a2481
Revises: f83026cf151c
Create Date: 2023-06-28 13:36:13.228049

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '00995c1a2481'
down_revision = 'f83026cf151c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
