"""test running migrations

Revision ID: 011d647ef373
Revises: fb518b3b03c5
Create Date: 2023-06-28 13:22:55.937138

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '011d647ef373'
down_revision = 'fb518b3b03c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
