"""test running migrations

Revision ID: 01c5004aef02
Revises: f2ed85abce84
Create Date: 2023-06-28 18:09:42.258262

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '01c5004aef02'
down_revision = 'f2ed85abce84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
