"""test running migrations

Revision ID: 02837d8cad68
Revises: 8c2d69c23ddb
Create Date: 2023-06-28 15:04:58.330018

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '02837d8cad68'
down_revision = '8c2d69c23ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
