"""test running migrations

Revision ID: 03f4a45ea960
Revises: acb5f8c2a0be
Create Date: 2023-06-28 18:23:13.420559

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03f4a45ea960'
down_revision = 'acb5f8c2a0be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
