"""test running migrations

Revision ID: 05cee683dd72
Revises: c14afabeecc5
Create Date: 2023-06-28 17:44:04.528542

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05cee683dd72'
down_revision = 'c14afabeecc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
