"""test running migrations

Revision ID: 05d2b4bb98d9
Revises: 3b378f5e09d0
Create Date: 2023-06-28 15:23:37.990863

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05d2b4bb98d9'
down_revision = '3b378f5e09d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
