"""test running migrations

Revision ID: 065d048e7dbb
Revises: c65edfac4c5d
Create Date: 2023-06-28 15:08:39.852003

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '065d048e7dbb'
down_revision = 'c65edfac4c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
