"""test running migrations

Revision ID: 068cb9d5e55a
Revises: 253386b1886c
Create Date: 2023-06-27 21:06:17.637193

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '068cb9d5e55a'
down_revision = '253386b1886c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
