"""test running migrations

Revision ID: 069fc3086bcc
Revises: 00995c1a2481
Create Date: 2023-06-28 13:36:32.804807

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '069fc3086bcc'
down_revision = '00995c1a2481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
