"""test running migrations

Revision ID: 07a97df0224b
Revises: 0a5abb640fa2
Create Date: 2023-06-28 18:30:01.856906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '07a97df0224b'
down_revision = '0a5abb640fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
