"""test running migrations

Revision ID: 0888d1ad8089
Revises: e751f49c031a
Create Date: 2023-06-28 14:29:45.650346

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0888d1ad8089'
down_revision = 'e751f49c031a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
