"""test running migrations

Revision ID: 0a5abb640fa2
Revises: b045a2d41e6a
Create Date: 2023-06-28 18:29:52.793009

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a5abb640fa2'
down_revision = 'b045a2d41e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
