"""test running migrations

Revision ID: 0ce9c99b612c
Revises: 7a13c5f8ed9b
Create Date: 2023-06-28 14:22:10.582452

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0ce9c99b612c'
down_revision = '7a13c5f8ed9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
