"""test running migrations

Revision ID: 0e6bdf8b91e1
Revises: cc88d46ba7c8
Create Date: 2023-06-27 20:24:37.852584

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0e6bdf8b91e1'
down_revision = 'cc88d46ba7c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
