"""test running migrations

Revision ID: 107116fbbe92
Revises: dee4b1242e5e
Create Date: 2023-06-28 18:29:04.209224

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '107116fbbe92'
down_revision = 'dee4b1242e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
