"""test running migrations

Revision ID: 12116f5143aa
Revises: 165cc8ec075f
Create Date: 2023-06-28 12:16:50.908054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '12116f5143aa'
down_revision = '165cc8ec075f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
