"""test running migrations

Revision ID: 1257803a5062
Revises: e8b5e28f9a58
Create Date: 2023-06-28 17:59:02.627790

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1257803a5062'
down_revision = 'e8b5e28f9a58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
