"""test running migrations

Revision ID: 125fb991a549
Revises: 0888d1ad8089
Create Date: 2023-06-28 14:34:58.637982

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '125fb991a549'
down_revision = '0888d1ad8089'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
