"""test running migrations

Revision ID: 12676cb9a0de
Revises: 1257803a5062
Create Date: 2023-06-28 18:00:06.145609

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '12676cb9a0de'
down_revision = '1257803a5062'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
