"""test running migrations

Revision ID: 127531b4236b
Revises: 1a2f4a77e9c6
Create Date: 2023-06-28 15:52:08.293115

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '127531b4236b'
down_revision = '1a2f4a77e9c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
