"""test running migrations

Revision ID: 149e737d02ee
Revises: 03f4a45ea960
Create Date: 2023-06-28 18:23:31.398331

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '149e737d02ee'
down_revision = '03f4a45ea960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
