"""test running migrations

Revision ID: 165cc8ec075f
Revises: c2bb9e211bce
Create Date: 2023-06-28 12:15:50.737040

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '165cc8ec075f'
down_revision = 'c2bb9e211bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
