"""test running migrations

Revision ID: 180cd0e0afbd
Revises: ab28f02024ce
Create Date: 2023-06-28 18:17:41.002786

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '180cd0e0afbd'
down_revision = 'ab28f02024ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
