"""test running migrations

Revision ID: 1886ff716afe
Revises: 5d0686061fbb
Create Date: 2023-06-28 15:02:42.905828

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1886ff716afe'
down_revision = '5d0686061fbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
