"""test running migrations

Revision ID: 19af320b5ce2
Revises: 33e09aed27e0
Create Date: 2023-06-28 17:53:43.978623

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '19af320b5ce2'
down_revision = '33e09aed27e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
