"""test running migrations

Revision ID: 1a2f4a77e9c6
Revises: 3fae10e6750b
Create Date: 2023-06-28 15:49:49.426894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a2f4a77e9c6'
down_revision = '3fae10e6750b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
