"""test running migrations

Revision ID: 1ac540e433d8
Revises: ec990fe76c03
Create Date: 2023-06-27 20:22:15.158733

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ac540e433d8'
down_revision = 'ec990fe76c03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
