"""test running migrations

Revision ID: 1ad2b98e07ef
Revises: 149e737d02ee
Create Date: 2023-06-28 18:23:34.903721

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ad2b98e07ef'
down_revision = '149e737d02ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
