"""test running migrations

Revision ID: 1c12279702a6
Revises: c289f848565c
Create Date: 2023-06-28 16:50:23.836181

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1c12279702a6'
down_revision = 'c289f848565c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
