"""test running migrations

Revision ID: 1d77cb453a8b
Revises: 107116fbbe92
Create Date: 2023-06-28 18:29:14.778543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1d77cb453a8b'
down_revision = '107116fbbe92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
