"""test running migrations

Revision ID: 1df883e42af8
Revises: f56c6267b9db
Create Date: 2023-06-27 20:52:00.588055

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1df883e42af8'
down_revision = 'f56c6267b9db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
