"""test running migrations

Revision ID: 1f40d3ba31e1
Revises: bcc47a742d82
Create Date: 2023-06-28 14:58:07.874708

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1f40d3ba31e1'
down_revision = 'bcc47a742d82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
