"""test running migrations

Revision ID: 2006078b7e92
Revises: c22bd041722f
Create Date: 2023-06-28 15:14:36.102357

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2006078b7e92'
down_revision = 'c22bd041722f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
