"""test running migrations

Revision ID: 200f06faf721
Revises: 8b64c41379b6
Create Date: 2023-06-28 13:31:55.493008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '200f06faf721'
down_revision = '8b64c41379b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
