"""test running migrations

Revision ID: 21fa2e4e746c
Revises: 37473b482264
Create Date: 2023-06-28 15:17:51.597522

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '21fa2e4e746c'
down_revision = '37473b482264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
