"""test running migrations

Revision ID: 2208c407b97b
Revises: 2fa7f7d446c5
Create Date: 2023-06-28 15:33:46.720264

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2208c407b97b'
down_revision = '2fa7f7d446c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
