"""test running migrations

Revision ID: 222af2db5d14
Revises: bc0e390283fc
Create Date: 2023-06-28 16:47:24.004791

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '222af2db5d14'
down_revision = 'bc0e390283fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
