"""test running migrations

Revision ID: 227b1694011f
Revises: c7198605f587
Create Date: 2023-06-28 14:09:56.130425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '227b1694011f'
down_revision = 'c7198605f587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
