"""test running migrations

Revision ID: 2327b3250e48
Revises: 30b94a5b093b
Create Date: 2023-06-27 20:33:51.000803

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2327b3250e48'
down_revision = '30b94a5b093b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
