"""test running migrations

Revision ID: 246ae849e043
Revises: aeffeff49d19
Create Date: 2023-06-28 18:06:43.569778

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '246ae849e043'
down_revision = 'aeffeff49d19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
