"""test running migrations

Revision ID: 24969f1f863e
Revises: 83f67083270c
Create Date: 2023-06-28 15:07:46.879130

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '24969f1f863e'
down_revision = '83f67083270c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
