"""test running migrations

Revision ID: 24a638c8a891
Revises: e7358b6f9572
Create Date: 2023-06-28 18:05:59.413076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '24a638c8a891'
down_revision = 'e7358b6f9572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
