"""test running migrations

Revision ID: 252e4ef0a565
Revises: 2208c407b97b
Create Date: 2023-06-28 15:34:00.820000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '252e4ef0a565'
down_revision = '2208c407b97b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
