"""test running migrations

Revision ID: 253386b1886c
Revises: af14a323cda1
Create Date: 2023-06-27 21:06:04.207361

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '253386b1886c'
down_revision = 'af14a323cda1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
