"""test running migrations

Revision ID: 25a6a75d7a12
Revises: d3b8113e73ea
Create Date: 2023-06-28 12:36:57.026668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '25a6a75d7a12'
down_revision = 'd3b8113e73ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
