"""test running migrations

Revision ID: 267db9e5c7b4
Revises: 05cee683dd72
Create Date: 2023-06-28 17:44:49.495206

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '267db9e5c7b4'
down_revision = '05cee683dd72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
