"""test running migrations

Revision ID: 28c431603c75
Revises: 8ef08a2a475a
Create Date: 2023-06-28 14:16:20.666046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '28c431603c75'
down_revision = '8ef08a2a475a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
