"""test running migrations

Revision ID: 29ccb95f1d28
Revises: 760a57b2dfde
Create Date: 2023-06-28 15:44:43.530580

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '29ccb95f1d28'
down_revision = '760a57b2dfde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
