"""test running migrations

Revision ID: 2a746e1dde88
Revises: 6955d5a102a7
Create Date: 2023-06-28 13:18:18.766105

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a746e1dde88'
down_revision = '6955d5a102a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
