"""test running migrations

Revision ID: 2d05a51fab7c
Revises: 74e764357650
Create Date: 2023-06-28 12:15:08.694150

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2d05a51fab7c'
down_revision = '74e764357650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
