"""test running migrations

Revision ID: 2d2047fe3075
Revises: 0086892c604f
Create Date: 2023-06-28 16:41:30.283894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2d2047fe3075'
down_revision = '0086892c604f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
