"""test running migrations

Revision ID: 2da4e67221a2
Revises: 7960a06e9f04
Create Date: 2023-06-28 16:35:45.735002

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2da4e67221a2'
down_revision = '7960a06e9f04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
