"""test running migrations

Revision ID: 2ecc7c99c51d
Revises: d9d3c86ea911
Create Date: 2023-06-28 13:15:18.965187

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2ecc7c99c51d'
down_revision = 'd9d3c86ea911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
