"""test running migrations

Revision ID: 2ed1d53fe36e
Revises: 417a5650e19f
Create Date: 2023-06-28 15:28:57.963828

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2ed1d53fe36e'
down_revision = '417a5650e19f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
