"""test running migrations

Revision ID: 2fa7f7d446c5
Revises: 49315c7106da
Create Date: 2023-06-28 15:32:16.832187

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2fa7f7d446c5'
down_revision = '49315c7106da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
