"""test running migrations

Revision ID: 301b13568741
Revises: 655168e96ea8
Create Date: 2023-06-28 15:16:48.071205

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '301b13568741'
down_revision = '655168e96ea8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
