"""test running migrations

Revision ID: 30b94a5b093b
Revises: 917c6416223c
Create Date: 2023-06-27 20:33:16.627249

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30b94a5b093b'
down_revision = '917c6416223c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
