"""test running migrations

Revision ID: 323921059531
Revises: 2da4e67221a2
Create Date: 2023-06-28 16:36:48.204866

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '323921059531'
down_revision = '2da4e67221a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
