"""test running migrations

Revision ID: 3246719f5e7a
Revises: fc17514c8d0b
Create Date: 2023-06-28 14:27:10.946819

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3246719f5e7a'
down_revision = 'fc17514c8d0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
