"""test running migrations

Revision ID: 327b4a9e6626
Revises: 852cedd5c88d
Create Date: 2023-06-28 17:55:06.469998

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '327b4a9e6626'
down_revision = '852cedd5c88d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
