"""test running migrations

Revision ID: 33e09aed27e0
Revises: 8417f06f2143
Create Date: 2023-06-28 17:52:31.489686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '33e09aed27e0'
down_revision = '8417f06f2143'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
