"""test running migrations

Revision ID: 342cd826522d
Revises: d1495cddf065
Create Date: 2023-06-28 15:10:08.526249

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '342cd826522d'
down_revision = 'd1495cddf065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
