"""test running migrations

Revision ID: 35e63531f9aa
Revises: aac7a298358b
Create Date: 2023-06-28 13:38:16.377244

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '35e63531f9aa'
down_revision = 'aac7a298358b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
