"""test running migrations

Revision ID: 37473b482264
Revises: 301b13568741
Create Date: 2023-06-28 15:17:19.193110

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '37473b482264'
down_revision = '301b13568741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
