"""test running migrations

Revision ID: 3b378f5e09d0
Revises: 3dec41c71433
Create Date: 2023-06-28 15:21:11.262200

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3b378f5e09d0'
down_revision = '3dec41c71433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
