"""test running migrations

Revision ID: 3c8c68f5f332
Revises: 7c4261b69f73
Create Date: 2023-06-28 14:55:11.932660

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3c8c68f5f332'
down_revision = '7c4261b69f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
