"""test running migrations

Revision ID: 3daecadd489d
Revises: b5e641d5a462
Create Date: 2023-06-28 16:42:16.151677

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3daecadd489d'
down_revision = 'b5e641d5a462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
