"""test running migrations

Revision ID: 3dec41c71433
Revises: 85debfcc939d
Create Date: 2023-06-28 15:20:30.201023

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3dec41c71433'
down_revision = '85debfcc939d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
