"""test running migrations

Revision ID: 3e501d9496be
Revises: 200f06faf721
Create Date: 2023-06-28 13:34:39.152316

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3e501d9496be'
down_revision = '200f06faf721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
