"""test running migrations

Revision ID: 3f7c7956e2ed
Revises: 9259a94e33bc
Create Date: 2023-06-28 15:12:24.139734

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3f7c7956e2ed'
down_revision = '9259a94e33bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
