"""test running migrations

Revision ID: 3fae10e6750b
Revises: bfbe85dd9e7a
Create Date: 2023-06-28 15:45:04.917983

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3fae10e6750b'
down_revision = 'bfbe85dd9e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
