"""test running migrations

Revision ID: 409ae9ed1a36
Revises: 7da3480374ba
Create Date: 2023-06-28 13:43:03.559804

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '409ae9ed1a36'
down_revision = '7da3480374ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
