"""test running migrations

Revision ID: 4135d89ef3bb
Revises: 327b4a9e6626
Create Date: 2023-06-28 17:55:59.419318

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4135d89ef3bb'
down_revision = '327b4a9e6626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
