"""test running migrations

Revision ID: 414a0617500e
Revises: 588070671cad
Create Date: 2023-06-28 11:30:23.520624

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '414a0617500e'
down_revision = '588070671cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
