"""test running migrations

Revision ID: 417a5650e19f
Revises: 05d2b4bb98d9
Create Date: 2023-06-28 15:28:50.923296

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '417a5650e19f'
down_revision = '05d2b4bb98d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
