"""test running migrations

Revision ID: 42e7739a7031
Revises: 7fad27e97185
Create Date: 2023-06-28 12:02:42.719268

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42e7739a7031'
down_revision = '7fad27e97185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
