"""test running migrations

Revision ID: 447146e0a5c7
Revises: bb3a3d15eaf3
Create Date: 2023-06-27 20:53:49.212250

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '447146e0a5c7'
down_revision = 'bb3a3d15eaf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
