"""test running migrations

Revision ID: 4678cdf9c813
Revises: 6aea470e9916
Create Date: 2023-06-28 18:25:27.491724

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4678cdf9c813'
down_revision = '6aea470e9916'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
