"""test running migrations

Revision ID: 4699e77e1735
Revises: dedb7a46dc2b
Create Date: 2023-06-27 20:16:17.544243

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4699e77e1735'
down_revision = 'dedb7a46dc2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
