"""test running migrations

Revision ID: 49315c7106da
Revises: 2ed1d53fe36e
Create Date: 2023-06-28 15:31:35.923340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '49315c7106da'
down_revision = '2ed1d53fe36e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
