"""test running migrations

Revision ID: 4dda6ba59c97
Revises: 869a154cab80
Create Date: 2023-06-28 14:36:20.383924

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4dda6ba59c97'
down_revision = '869a154cab80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
