"""test running migrations

Revision ID: 4e16cee4bee5
Revises: 9e8a8024ca00
Create Date: 2023-06-28 16:51:58.406995

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4e16cee4bee5'
down_revision = '9e8a8024ca00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
