"""test running migrations

Revision ID: 5140e8558821
Revises: b6377ec0a202
Create Date: 2023-06-28 16:45:10.976686

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5140e8558821'
down_revision = 'b6377ec0a202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
