"""test running migrations

Revision ID: 528d67e2d6ca
Revises: 6eb3c3567c4b
Create Date: 2023-06-28 12:40:04.557211

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '528d67e2d6ca'
down_revision = '6eb3c3567c4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
