"""test running migrations

Revision ID: 53e385969fe4
Revises: 02837d8cad68
Create Date: 2023-06-28 15:05:35.569439

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '53e385969fe4'
down_revision = '02837d8cad68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
