"""test running migrations

Revision ID: 53fe2741969a
Revises: 82e01fadbb45
Create Date: 2023-06-28 18:22:33.776076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '53fe2741969a'
down_revision = '82e01fadbb45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
