"""test running migrations

Revision ID: 561bb4b0dfac
Revises: ed5420639925
Create Date: 2023-06-28 18:15:16.690139

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '561bb4b0dfac'
down_revision = 'ed5420639925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
