"""test running migrations

Revision ID: 576ee11e7b10
Revises: a7894f082fdb
Create Date: 2023-06-27 20:58:02.245269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '576ee11e7b10'
down_revision = 'a7894f082fdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
