"""test running migrations

Revision ID: 588070671cad
Revises: 8d612dfa25f6
Create Date: 2023-06-28 11:26:07.638482

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '588070671cad'
down_revision = '8d612dfa25f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
