"""test running migrations

Revision ID: 5a4b7f9b9aa5
Revises: 5c8e4fca4a60
Create Date: 2023-06-28 14:22:58.859419

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5a4b7f9b9aa5'
down_revision = '5c8e4fca4a60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
