"""test running migrations

Revision ID: 5a6a1a7f1f30
Revises: be3c4a7eee08
Create Date: 2023-06-28 14:26:28.206689

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5a6a1a7f1f30'
down_revision = 'be3c4a7eee08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
