"""test running migrations

Revision ID: 5c8e4fca4a60
Revises: 0ce9c99b612c
Create Date: 2023-06-28 14:22:40.835890

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5c8e4fca4a60'
down_revision = '0ce9c99b612c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
