"""test running migrations

Revision ID: 5d0686061fbb
Revises: c0de7524fcea
Create Date: 2023-06-28 15:02:26.714857

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5d0686061fbb'
down_revision = 'c0de7524fcea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
