"""test running migrations

Revision ID: 5f0bbe10ce54
Revises: ff8a8e906d43
Create Date: 2023-06-28 13:47:44.488707

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5f0bbe10ce54'
down_revision = 'ff8a8e906d43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
