"""test running migrations

Revision ID: 5fbe75c2f725
Revises: 246ae849e043
Create Date: 2023-06-28 18:06:46.395140

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5fbe75c2f725'
down_revision = '246ae849e043'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
