"""test running migrations

Revision ID: 6322bb2bda81
Revises: aa51ae2cf2e5
Create Date: 2023-06-28 16:19:07.488893

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6322bb2bda81'
down_revision = 'aa51ae2cf2e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
