"""test running migrations

Revision ID: 6349b24a75f7
Revises: cf6847448226
Create Date: 2023-06-28 15:00:53.438127

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6349b24a75f7'
down_revision = 'cf6847448226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
