"""test running migrations

Revision ID: 655168e96ea8
Revises: 88d12d471ec1
Create Date: 2023-06-28 15:15:55.630160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '655168e96ea8'
down_revision = '88d12d471ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
