"""test running migrations

Revision ID: 68157cd4d40e
Revises: b9e94ce82157
Create Date: 2023-06-28 17:40:16.373368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68157cd4d40e'
down_revision = 'b9e94ce82157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
