"""test running migrations

Revision ID: 6839eeec4eeb
Revises: 07a97df0224b
Create Date: 2023-06-28 18:30:09.297740

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6839eeec4eeb'
down_revision = '07a97df0224b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
