"""test running migrations

Revision ID: 6955d5a102a7
Revises: 2ecc7c99c51d
Create Date: 2023-06-28 13:17:31.486768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6955d5a102a7'
down_revision = '2ecc7c99c51d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
