"""test running migrations

Revision ID: 6ad8847014b6
Revises: 9b1f1b2c4b1d
Create Date: 2023-06-27 20:29:57.571796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6ad8847014b6'
down_revision = '9b1f1b2c4b1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
