"""test running migrations

Revision ID: 6aea470e9916
Revises: 1ad2b98e07ef
Create Date: 2023-06-28 18:25:24.015203

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6aea470e9916'
down_revision = '1ad2b98e07ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
