"""test running migrations

Revision ID: 6e31a3a2946b
Revises: b7124d8bf9e4
Create Date: 2023-06-27 20:55:16.301559

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e31a3a2946b'
down_revision = 'b7124d8bf9e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
