"""test running migrations

Revision ID: 6e8db39941da
Revises: 714bd00c9fc7
Create Date: 2023-06-27 20:38:53.020583

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e8db39941da'
down_revision = '714bd00c9fc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
