"""test running migrations

Revision ID: 6eb3c3567c4b
Revises: 8d10da7ed0d8
Create Date: 2023-06-28 12:38:31.897193

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6eb3c3567c4b'
down_revision = '8d10da7ed0d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
