"""test running migrations

Revision ID: 70821c3d2916
Revises: 53fe2741969a
Create Date: 2023-06-28 18:22:44.251412

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '70821c3d2916'
down_revision = '53fe2741969a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
