"""test running migrations

Revision ID: 714bd00c9fc7
Revises: 9bb6f3418e1e
Create Date: 2023-06-27 20:35:13.372466

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '714bd00c9fc7'
down_revision = '9bb6f3418e1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
