"""test running migrations

Revision ID: 71e74df3785f
Revises: 1886ff716afe
Create Date: 2023-06-28 15:03:01.419848

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71e74df3785f'
down_revision = '1886ff716afe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
