"""test running migrations

Revision ID: 71f72448328e
Revises: 267db9e5c7b4
Create Date: 2023-06-28 17:46:07.164152

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71f72448328e'
down_revision = '267db9e5c7b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
