"""test running migrations

Revision ID: 74e764357650
Revises: 7c474016e731
Create Date: 2023-06-28 12:14:32.655570

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '74e764357650'
down_revision = '7c474016e731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
