"""test running migrations

Revision ID: 760a57b2dfde
Revises: 879ce7a5cdd3
Create Date: 2023-06-28 15:38:28.104599

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '760a57b2dfde'
down_revision = '879ce7a5cdd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
