"""test running migrations

Revision ID: 76c50d0e56d7
Revises: dc559c97a417
Create Date: 2023-06-28 14:25:23.594323

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '76c50d0e56d7'
down_revision = 'dc559c97a417'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
