"""test running migrations

Revision ID: 772b7852455d
Revises: 71e74df3785f
Create Date: 2023-06-28 15:03:59.136774

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '772b7852455d'
down_revision = '71e74df3785f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
