"""test running migrations

Revision ID: 77cd80f93145
Revises: f4874c3d9755
Create Date: 2023-06-28 16:30:10.138474

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '77cd80f93145'
down_revision = 'f4874c3d9755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
