"""test running migrations

Revision ID: 77f41df78e91
Revises: 9afe965a26ed
Create Date: 2023-06-28 13:48:24.479956

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '77f41df78e91'
down_revision = '9afe965a26ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
