"""test running migrations

Revision ID: 7821af94eddc
Revises: ff00b468fa21
Create Date: 2023-06-28 16:28:16.975281

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7821af94eddc'
down_revision = 'ff00b468fa21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
