"""test running migrations

Revision ID: 78f7c0dacd91
Revises: eb8d895f82ef
Create Date: 2023-06-28 14:00:00.370419

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '78f7c0dacd91'
down_revision = 'eb8d895f82ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
