"""test running migrations

Revision ID: 7940228eb0e2
Revises: 12676cb9a0de
Create Date: 2023-06-28 18:00:44.909455

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7940228eb0e2'
down_revision = '12676cb9a0de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
