"""test running migrations

Revision ID: 7960a06e9f04
Revises: d7af50807730
Create Date: 2023-06-28 16:33:43.273225

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7960a06e9f04'
down_revision = 'd7af50807730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
