"""test running migrations

Revision ID: 79d4cfc39218
Revises: 3daecadd489d
Create Date: 2023-06-28 16:42:28.242980

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '79d4cfc39218'
down_revision = '3daecadd489d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
