"""test running migrations

Revision ID: 79df064af68d
Revises: 77cd80f93145
Create Date: 2023-06-28 16:30:34.300415

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '79df064af68d'
down_revision = '77cd80f93145'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
