"""test running migrations

Revision ID: 7a13c5f8ed9b
Revises: 28c431603c75
Create Date: 2023-06-28 14:21:08.704962

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7a13c5f8ed9b'
down_revision = '28c431603c75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
