"""test running migrations

Revision ID: 7babc3c923da
Revises: d4bc7101b709
Create Date: 2023-06-28 15:19:44.017049

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7babc3c923da'
down_revision = 'd4bc7101b709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
