"""test running migrations

Revision ID: 7c27277806ee
Revises: b827ecbbc218
Create Date: 2023-06-28 13:52:29.930112

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7c27277806ee'
down_revision = 'b827ecbbc218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
