"""test running migrations

Revision ID: 7c4261b69f73
Revises: a9e660cae0a3
Create Date: 2023-06-28 14:54:31.245160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7c4261b69f73'
down_revision = 'a9e660cae0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
