"""test running migrations

Revision ID: 7c474016e731
Revises: 95f74ad757df
Create Date: 2023-06-28 12:13:04.633209

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7c474016e731'
down_revision = '95f74ad757df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
