"""test running migrations

Revision ID: 7da3480374ba
Revises: d2d408a62ac6
Create Date: 2023-06-28 13:42:17.062630

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7da3480374ba'
down_revision = 'd2d408a62ac6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
