"""test running migrations

Revision ID: 7fad27e97185
Revises: 414a0617500e
Create Date: 2023-06-28 12:02:24.702443

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7fad27e97185'
down_revision = '414a0617500e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
