"""test running migrations

Revision ID: 80713e3b2f8a
Revises: 8910b261e591
Create Date: 2023-06-27 21:07:38.672435

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '80713e3b2f8a'
down_revision = '8910b261e591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
