"""test running migrations

Revision ID: 82e01fadbb45
Revises: 180cd0e0afbd
Create Date: 2023-06-28 18:20:32.694641

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '82e01fadbb45'
down_revision = '180cd0e0afbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
