"""test running migrations

Revision ID: 83f67083270c
Revises: 53e385969fe4
Create Date: 2023-06-28 15:07:42.153498

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '83f67083270c'
down_revision = '53e385969fe4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
