"""test running migrations

Revision ID: 8417f06f2143
Revises: 71f72448328e
Create Date: 2023-06-28 17:49:35.570355

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8417f06f2143'
down_revision = '71f72448328e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
