"""test running migrations

Revision ID: 843ef4312a29
Revises: fa0d8ebae33b
Create Date: 2023-06-28 16:15:11.572435

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '843ef4312a29'
down_revision = 'fa0d8ebae33b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
