"""test running migrations

Revision ID: 852cedd5c88d
Revises: 19af320b5ce2
Create Date: 2023-06-28 17:54:43.621277

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '852cedd5c88d'
down_revision = '19af320b5ce2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
