"""test running migrations

Revision ID: 85debfcc939d
Revises: 7babc3c923da
Create Date: 2023-06-28 15:19:55.336351

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '85debfcc939d'
down_revision = '7babc3c923da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
