"""test running migrations

Revision ID: 869a154cab80
Revises: 125fb991a549
Create Date: 2023-06-28 14:35:29.249196

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '869a154cab80'
down_revision = '125fb991a549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
