"""test running migrations

Revision ID: 879ce7a5cdd3
Revises: 252e4ef0a565
Create Date: 2023-06-28 15:34:31.144849

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '879ce7a5cdd3'
down_revision = '252e4ef0a565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
