"""test running migrations

Revision ID: 87f4c9b9540b
Revises: b97076f76316
Create Date: 2023-06-27 21:01:03.864179

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '87f4c9b9540b'
down_revision = 'b97076f76316'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
