"""test running migrations

Revision ID: 88d12d471ec1
Revises: 9900012516a0
Create Date: 2023-06-28 15:15:32.980995

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '88d12d471ec1'
down_revision = '9900012516a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
