"""test running migrations

Revision ID: 8910b261e591
Revises: 957e2892b614
Create Date: 2023-06-27 21:07:26.760615

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8910b261e591'
down_revision = '957e2892b614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
