"""test running migrations

Revision ID: 8923936569d0
Revises: 87f4c9b9540b
Create Date: 2023-06-27 21:02:53.855214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8923936569d0'
down_revision = '87f4c9b9540b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
