"""test running migrations

Revision ID: 8a6e7edb36f1
Revises: bd755bc20bbe
Create Date: 2023-06-27 20:26:26.865903

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8a6e7edb36f1'
down_revision = 'bd755bc20bbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
