"""test running migrations

Revision ID: 8b64c41379b6
Revises: 011d647ef373
Create Date: 2023-06-28 13:23:13.174929

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8b64c41379b6'
down_revision = '011d647ef373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
