"""test running migrations

Revision ID: 8c29bf90e5c7
Revises: 6e8db39941da
Create Date: 2023-06-27 20:39:30.079033

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8c29bf90e5c7'
down_revision = '6e8db39941da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
