"""test running migrations

Revision ID: 8c2d69c23ddb
Revises: 9ce3aea1e186
Create Date: 2023-06-28 15:04:52.322334

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8c2d69c23ddb'
down_revision = '9ce3aea1e186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
