"""test running migrations

Revision ID: 8d10da7ed0d8
Revises: 25a6a75d7a12
Create Date: 2023-06-28 12:38:12.446588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8d10da7ed0d8'
down_revision = '25a6a75d7a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
