"""test running migrations

Revision ID: 8d612dfa25f6
Revises: 80713e3b2f8a
Create Date: 2023-06-27 21:07:47.788291

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8d612dfa25f6'
down_revision = '80713e3b2f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
