"""test running migrations

Revision ID: 8eb1a30997dc
Revises: 5140e8558821
Create Date: 2023-06-28 16:45:54.668108

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8eb1a30997dc'
down_revision = '5140e8558821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
