"""test running migrations

Revision ID: 8ef08a2a475a
Revises: b0c1c047fd77
Create Date: 2023-06-28 14:10:36.452675

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8ef08a2a475a'
down_revision = 'b0c1c047fd77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
