"""test running migrations

Revision ID: 9014cfc31702
Revises: 2006078b7e92
Create Date: 2023-06-28 15:14:45.896150

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9014cfc31702'
down_revision = '2006078b7e92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
