"""test running migrations

Revision ID: 902163b7f93f
Revises: 70821c3d2916
Create Date: 2023-06-28 18:22:48.235432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '902163b7f93f'
down_revision = '70821c3d2916'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
