"""test running migrations

Revision ID: 917c6416223c
Revises: d14b0fccf17c
Create Date: 2023-06-27 20:33:04.490814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '917c6416223c'
down_revision = 'd14b0fccf17c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
