"""test running migrations

Revision ID: 9259a94e33bc
Revises: 342cd826522d
Create Date: 2023-06-28 15:10:59.078849

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9259a94e33bc'
down_revision = '342cd826522d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
