"""test running migrations

Revision ID: 934e9ca26526
Revises: 951c67d240ec
Create Date: 2023-06-27 20:46:58.410814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '934e9ca26526'
down_revision = '951c67d240ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
