"""test running migrations

Revision ID: 957e2892b614
Revises: 068cb9d5e55a
Create Date: 2023-06-27 21:06:58.910853

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '957e2892b614'
down_revision = '068cb9d5e55a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
