"""test running migrations

Revision ID: 958483ef18f7
Revises: db63149f929c
Create Date: 2023-06-28 12:04:54.957739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '958483ef18f7'
down_revision = 'db63149f929c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
