"""test running migrations

Revision ID: 95f74ad757df
Revises: bc56084c1283
Create Date: 2023-06-28 12:12:35.435776

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '95f74ad757df'
down_revision = 'bc56084c1283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
