"""test running migrations

Revision ID: 95fbd3074227
Revises: 561bb4b0dfac
Create Date: 2023-06-28 18:16:10.772432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '95fbd3074227'
down_revision = '561bb4b0dfac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
