"""test running migrations

Revision ID: 9843375f3593
Revises: a43421bb43da
Create Date: 2023-06-28 13:51:00.928376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9843375f3593'
down_revision = 'a43421bb43da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
