"""test running migrations

Revision ID: 9900012516a0
Revises: 9014cfc31702
Create Date: 2023-06-28 15:15:25.846595

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9900012516a0'
down_revision = '9014cfc31702'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
