"""test running migrations

Revision ID: 9afe965a26ed
Revises: 5f0bbe10ce54
Create Date: 2023-06-28 13:48:04.240792

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9afe965a26ed'
down_revision = '5f0bbe10ce54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
