"""test running migrations

Revision ID: 9b1f1b2c4b1d
Revises: 8a6e7edb36f1
Create Date: 2023-06-27 20:28:50.395664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9b1f1b2c4b1d'
down_revision = '8a6e7edb36f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
