"""test running migrations

Revision ID: 9bb6f3418e1e
Revises: 2327b3250e48
Create Date: 2023-06-27 20:34:11.205382

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9bb6f3418e1e'
down_revision = '2327b3250e48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
