"""test running migrations

Revision ID: 9ce3aea1e186
Revises: 772b7852455d
Create Date: 2023-06-28 15:04:47.966717

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9ce3aea1e186'
down_revision = '772b7852455d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
