"""test running migrations

Revision ID: 9e482eab9dae
Revises: 528d67e2d6ca
Create Date: 2023-06-28 13:09:56.799381

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9e482eab9dae'
down_revision = '528d67e2d6ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
