"""test running migrations

Revision ID: 9e8a8024ca00
Revises: 1c12279702a6
Create Date: 2023-06-28 16:51:23.329059

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9e8a8024ca00'
down_revision = '1c12279702a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
