"""test running migrations

Revision ID: 9ec6afb38039
Revises: a428fdb77189
Create Date: 2023-06-28 12:18:30.506433

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9ec6afb38039'
down_revision = 'a428fdb77189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
