"""test running migrations

Revision ID: a0d31f94b675
Revises: 934e9ca26526
Create Date: 2023-06-27 20:48:46.257886

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a0d31f94b675'
down_revision = '934e9ca26526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
