"""test running migrations

Revision ID: a35ac564f7bb
Revises: 3e501d9496be
Create Date: 2023-06-28 13:34:59.835203

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a35ac564f7bb'
down_revision = '3e501d9496be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
