"""test running migrations

Revision ID: a428fdb77189
Revises: e7b32f68b207
Create Date: 2023-06-28 12:17:34.392376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a428fdb77189'
down_revision = 'e7b32f68b207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
