"""test running migrations

Revision ID: a43421bb43da
Revises: 77f41df78e91
Create Date: 2023-06-28 13:49:17.915468

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a43421bb43da'
down_revision = '77f41df78e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
