"""test running migrations

Revision ID: a6bd5fe81b64
Revises: 3c8c68f5f332
Create Date: 2023-06-28 14:55:34.837713

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6bd5fe81b64'
down_revision = '3c8c68f5f332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
