"""test running migrations

Revision ID: a7894f082fdb
Revises: 6e31a3a2946b
Create Date: 2023-06-27 20:56:23.538029

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7894f082fdb'
down_revision = '6e31a3a2946b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
