"""test running migrations

Revision ID: a8d32ee08819
Revises: 95fbd3074227
Create Date: 2023-06-28 18:16:55.009831

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8d32ee08819'
down_revision = '95fbd3074227'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
