"""test running migrations

Revision ID: a9e660cae0a3
Revises: afa16ea0b171
Create Date: 2023-06-28 14:53:18.982970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a9e660cae0a3'
down_revision = 'afa16ea0b171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
