"""test running migrations

Revision ID: aac7a298358b
Revises: dcece2a9fa46
Create Date: 2023-06-28 13:37:26.611867

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aac7a298358b'
down_revision = 'dcece2a9fa46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
