"""test running migrations

Revision ID: ab28f02024ce
Revises: a8d32ee08819
Create Date: 2023-06-28 18:17:00.416392

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ab28f02024ce'
down_revision = 'a8d32ee08819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
