"""test running migrations

Revision ID: ab59be5ebb4a
Revises: b2b2903cd414
Create Date: 2023-06-27 20:20:57.120107

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ab59be5ebb4a'
down_revision = 'b2b2903cd414'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
