"""test running migrations

Revision ID: ac7e2fc9683b
Revises: f9c49d2c8fd8
Create Date: 2023-06-28 13:40:51.178224

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ac7e2fc9683b'
down_revision = 'f9c49d2c8fd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
