"""test running migrations

Revision ID: acb5f8c2a0be
Revises: 902163b7f93f
Create Date: 2023-06-28 18:23:08.548969

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'acb5f8c2a0be'
down_revision = '902163b7f93f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
