"""test running migrations

Revision ID: aef493d89b67
Revises: c2a56215d78d
Create Date: 2023-06-28 16:25:02.572673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aef493d89b67'
down_revision = 'c2a56215d78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
