"""test running migrations

Revision ID: aeffeff49d19
Revises: 24a638c8a891
Create Date: 2023-06-28 18:06:40.361428

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aeffeff49d19'
down_revision = '24a638c8a891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
