"""test running migrations

Revision ID: af14a323cda1
Revises: 8923936569d0
Create Date: 2023-06-27 21:03:51.145409

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af14a323cda1'
down_revision = '8923936569d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
