"""test running migrations

Revision ID: afa16ea0b171
Revises: 4dda6ba59c97
Create Date: 2023-06-28 14:50:21.347484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'afa16ea0b171'
down_revision = '4dda6ba59c97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
