"""test running migrations

Revision ID: b045a2d41e6a
Revises: ce0d70df9a18
Create Date: 2023-06-28 18:29:40.702491

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b045a2d41e6a'
down_revision = 'ce0d70df9a18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
