"""test running migrations

Revision ID: b058958673f7
Revises: 35e63531f9aa
Create Date: 2023-06-28 13:38:28.122786

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b058958673f7'
down_revision = '35e63531f9aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
