"""test running migrations

Revision ID: b0c1c047fd77
Revises: 227b1694011f
Create Date: 2023-06-28 14:10:04.081735

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b0c1c047fd77'
down_revision = '227b1694011f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
