"""test running migrations

Revision ID: b2b2903cd414
Revises: ed38198aeb4c
Create Date: 2023-06-27 20:20:04.407968

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b2b2903cd414'
down_revision = 'ed38198aeb4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
