"""test running migrations

Revision ID: b5aeba911a95
Revises: 127531b4236b
Create Date: 2023-06-28 15:54:58.496073

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5aeba911a95'
down_revision = '127531b4236b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
