"""test running migrations

Revision ID: b5e641d5a462
Revises: 2d2047fe3075
Create Date: 2023-06-28 16:42:06.514785

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5e641d5a462'
down_revision = '2d2047fe3075'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
