"""test running migrations

Revision ID: b6377ec0a202
Revises: 79d4cfc39218
Create Date: 2023-06-28 16:44:31.933159

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b6377ec0a202'
down_revision = '79d4cfc39218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
