"""test running migrations

Revision ID: b7124d8bf9e4
Revises: 447146e0a5c7
Create Date: 2023-06-27 20:54:39.795904

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b7124d8bf9e4'
down_revision = '447146e0a5c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
