"""test running migrations

Revision ID: b827ecbbc218
Revises: 9843375f3593
Create Date: 2023-06-28 13:51:24.159358

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b827ecbbc218'
down_revision = '9843375f3593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
