"""test running migrations

Revision ID: b97076f76316
Revises: 576ee11e7b10
Create Date: 2023-06-27 21:00:05.884390

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b97076f76316'
down_revision = '576ee11e7b10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
