"""test running migrations

Revision ID: b9e94ce82157
Revises: 4e16cee4bee5
Create Date: 2023-06-28 16:52:49.764685

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b9e94ce82157'
down_revision = '4e16cee4bee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
