"""test running migrations

Revision ID: bb3a3d15eaf3
Revises: 1df883e42af8
Create Date: 2023-06-27 20:52:48.362751

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bb3a3d15eaf3'
down_revision = '1df883e42af8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
