"""test running migrations

Revision ID: bc0e390283fc
Revises: 8eb1a30997dc
Create Date: 2023-06-28 16:46:27.691269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bc0e390283fc'
down_revision = '8eb1a30997dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
