"""test running migrations

Revision ID: bc56084c1283
Revises: 958483ef18f7
Create Date: 2023-06-28 12:06:41.405307

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bc56084c1283'
down_revision = '958483ef18f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
