"""test running migrations

Revision ID: bcc47a742d82
Revises: a6bd5fe81b64
Create Date: 2023-06-28 14:57:18.987419

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bcc47a742d82'
down_revision = 'a6bd5fe81b64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
