"""test running migrations

Revision ID: bd755bc20bbe
Revises: 0e6bdf8b91e1
Create Date: 2023-06-27 20:25:46.389575

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd755bc20bbe'
down_revision = '0e6bdf8b91e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
