"""test running migrations

Revision ID: be3c4a7eee08
Revises: 76c50d0e56d7
Create Date: 2023-06-28 14:25:52.702301

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'be3c4a7eee08'
down_revision = '76c50d0e56d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
