"""test running migrations

Revision ID: beeacdfe596f
Revises: cf6ebc6b68f7
Create Date: 2023-06-28 12:04:12.450287

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'beeacdfe596f'
down_revision = 'cf6ebc6b68f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
