"""test running migrations

Revision ID: bfbe85dd9e7a
Revises: 29ccb95f1d28
Create Date: 2023-06-28 15:44:56.976719

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bfbe85dd9e7a'
down_revision = '29ccb95f1d28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
