"""test running migrations

Revision ID: c0de7524fcea
Revises: 6349b24a75f7
Create Date: 2023-06-28 15:02:11.431090

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0de7524fcea'
down_revision = '6349b24a75f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
