"""test running migrations

Revision ID: c14afabeecc5
Revises: 68157cd4d40e
Create Date: 2023-06-28 17:41:22.707177

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c14afabeecc5'
down_revision = '68157cd4d40e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
