"""test running migrations

Revision ID: c22bd041722f
Revises: 3f7c7956e2ed
Create Date: 2023-06-28 15:13:38.906938

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c22bd041722f'
down_revision = '3f7c7956e2ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
