"""test running migrations

Revision ID: c289f848565c
Revises: f8fd92952bfa
Create Date: 2023-06-28 16:49:34.583345

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c289f848565c'
down_revision = 'f8fd92952bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
