"""test running migrations

Revision ID: c2a56215d78d
Revises: c3aa0a11d0f1
Create Date: 2023-06-28 16:23:45.539611

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c2a56215d78d'
down_revision = 'c3aa0a11d0f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
