"""test running migrations

Revision ID: c2bb9e211bce
Revises: 2d05a51fab7c
Create Date: 2023-06-28 12:15:26.410167

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c2bb9e211bce'
down_revision = '2d05a51fab7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
