"""test running migrations

Revision ID: c357ee2ffee4
Revises: 7940228eb0e2
Create Date: 2023-06-28 18:01:38.313921

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c357ee2ffee4'
down_revision = '7940228eb0e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
