"""test running migrations

Revision ID: c3aa0a11d0f1
Revises: 6322bb2bda81
Create Date: 2023-06-28 16:23:22.864884

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c3aa0a11d0f1'
down_revision = '6322bb2bda81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
