"""test running migrations

Revision ID: c598d963f55c
Revises: aef493d89b67
Create Date: 2023-06-28 16:26:34.560159

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c598d963f55c'
down_revision = 'aef493d89b67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
