"""test running migrations

Revision ID: c5d5774b0160
Revises: 9ec6afb38039
Create Date: 2023-06-28 12:21:09.613563

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5d5774b0160'
down_revision = '9ec6afb38039'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
