"""test running migrations

Revision ID: c65edfac4c5d
Revises: 24969f1f863e
Create Date: 2023-06-28 15:08:26.718376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c65edfac4c5d'
down_revision = '24969f1f863e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
