"""test running migrations

Revision ID: c6b6923794de
Revises: 9e482eab9dae
Create Date: 2023-06-28 13:10:42.878584

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c6b6923794de'
down_revision = '9e482eab9dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
