"""test running migrations

Revision ID: c7198605f587
Revises: dd371f5d1ac8
Create Date: 2023-06-28 14:09:30.942804

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c7198605f587'
down_revision = 'dd371f5d1ac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
