"""test running migrations

Revision ID: cc88d46ba7c8
Revises: b1000bc52a33
Create Date: 2023-06-27 20:22:55.478405

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cc88d46ba7c8'
down_revision = 'b1000bc52a33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
