"""test running migrations

Revision ID: cdb1b06b8d15
Revises: e4819eae7fe6
Create Date: 2023-06-28 18:04:05.053485

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cdb1b06b8d15'
down_revision = 'e4819eae7fe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
