"""test running migrations

Revision ID: ce0d70df9a18
Revises: 1d77cb453a8b
Create Date: 2023-06-28 18:29:27.863843

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ce0d70df9a18'
down_revision = '1d77cb453a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
