"""test running migrations

Revision ID: ce2c90a6cb48
Revises: 78f7c0dacd91
Create Date: 2023-06-28 14:00:57.288005

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ce2c90a6cb48'
down_revision = '78f7c0dacd91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
