"""test running migrations

Revision ID: cf6847448226
Revises: 1f40d3ba31e1
Create Date: 2023-06-28 15:00:16.980217

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf6847448226'
down_revision = '1f40d3ba31e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
