"""test running migrations

Revision ID: cf6ebc6b68f7
Revises: 42e7739a7031
Create Date: 2023-06-28 12:03:47.572350

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf6ebc6b68f7'
down_revision = '42e7739a7031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
