"""test running migrations

Revision ID: d1495cddf065
Revises: 065d048e7dbb
Create Date: 2023-06-28 15:09:59.748911

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd1495cddf065'
down_revision = '065d048e7dbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
