"""test running migrations

Revision ID: d14b0fccf17c
Revises: f0891cc695a0
Create Date: 2023-06-27 20:31:52.309827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd14b0fccf17c'
down_revision = 'f0891cc695a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
