"""test running migrations

Revision ID: d2d408a62ac6
Revises: ac7e2fc9683b
Create Date: 2023-06-28 13:41:53.454183

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd2d408a62ac6'
down_revision = 'ac7e2fc9683b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
