"""test running migrations

Revision ID: d3b8113e73ea
Revises: c5d5774b0160
Create Date: 2023-06-28 12:21:49.409836

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3b8113e73ea'
down_revision = 'c5d5774b0160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
