"""test running migrations

Revision ID: d4bc7101b709
Revises: e61b2f0d2453
Create Date: 2023-06-28 15:19:23.945462

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4bc7101b709'
down_revision = 'e61b2f0d2453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
