"""test running migrations

Revision ID: d6021f98a55f
Revises: 5a4b7f9b9aa5
Create Date: 2023-06-28 14:23:35.847891

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd6021f98a55f'
down_revision = '5a4b7f9b9aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
