"""test running migrations

Revision ID: d7af50807730
Revises: ec3fceeb76e4
Create Date: 2023-06-28 16:33:13.893383

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7af50807730'
down_revision = 'ec3fceeb76e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
