"""test running migrations

Revision ID: d9d3c86ea911
Revises: c6b6923794de
Create Date: 2023-06-28 13:12:37.287115

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9d3c86ea911'
down_revision = 'c6b6923794de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
