"""test running migrations

Revision ID: db63149f929c
Revises: beeacdfe596f
Create Date: 2023-06-28 12:04:29.598825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'db63149f929c'
down_revision = 'beeacdfe596f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
