"""test running migrations

Revision ID: dc559c97a417
Revises: d6021f98a55f
Create Date: 2023-06-28 14:24:33.072462

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dc559c97a417'
down_revision = 'd6021f98a55f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
