"""test running migrations

Revision ID: dc6a11ca61b5
Revises: ab59be5ebb4a
Create Date: 2023-06-27 20:22:00.234165

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dc6a11ca61b5'
down_revision = 'ab59be5ebb4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
