"""test running migrations

Revision ID: dcece2a9fa46
Revises: 069fc3086bcc
Create Date: 2023-06-28 13:37:12.672673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dcece2a9fa46'
down_revision = '069fc3086bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
