"""test running migrations

Revision ID: dd371f5d1ac8
Revises: ce2c90a6cb48
Create Date: 2023-06-28 14:09:11.919041

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd371f5d1ac8'
down_revision = 'ce2c90a6cb48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
