"""test running migrations

Revision ID: dedb7a46dc2b
Revises: 5e7eb65e8267
Create Date: 2023-06-27 20:14:29.097870

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dedb7a46dc2b'
down_revision = '5e7eb65e8267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
