"""test running migrations

Revision ID: dee4b1242e5e
Revises: f252b81255b1
Create Date: 2023-06-28 18:28:56.162028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dee4b1242e5e'
down_revision = 'f252b81255b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
