"""test running migrations

Revision ID: e409675a11f8
Revises: f7ba4da908f7
Create Date: 2023-06-28 13:20:32.012313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e409675a11f8'
down_revision = 'f7ba4da908f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
