"""test running migrations

Revision ID: e4819eae7fe6
Revises: be293e4c0778
Create Date: 2023-06-28 18:03:56.790012

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e4819eae7fe6'
down_revision = 'be293e4c0778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
