"""test running migrations

Revision ID: e61b2f0d2453
Revises: 21fa2e4e746c
Create Date: 2023-06-28 15:19:11.509933

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e61b2f0d2453'
down_revision = '21fa2e4e746c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
