"""test running migrations

Revision ID: e7358b6f9572
Revises: 7c3abbdf4003
Create Date: 2023-06-28 18:05:48.176534

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e7358b6f9572'
down_revision = '7c3abbdf4003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
