"""test running migrations

Revision ID: e751f49c031a
Revises: 3246719f5e7a
Create Date: 2023-06-28 14:27:28.745581

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e751f49c031a'
down_revision = '3246719f5e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
