"""test running migrations

Revision ID: e7b32f68b207
Revises: 12116f5143aa
Create Date: 2023-06-28 12:17:08.960956

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e7b32f68b207'
down_revision = '12116f5143aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
