"""test running migrations

Revision ID: e8b5e28f9a58
Revises: 4135d89ef3bb
Create Date: 2023-06-28 17:58:28.263067

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e8b5e28f9a58'
down_revision = '4135d89ef3bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
