"""test running migrations

Revision ID: eb571c10a4d3
Revises: 4678cdf9c813
Create Date: 2023-06-28 18:25:30.575153

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb571c10a4d3'
down_revision = '4678cdf9c813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
