"""test running migrations

Revision ID: eb8d895f82ef
Revises: 7c27277806ee
Create Date: 2023-06-28 13:55:19.336793

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb8d895f82ef'
down_revision = '7c27277806ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
