"""test running migrations

Revision ID: ec3fceeb76e4
Revises: 79df064af68d
Create Date: 2023-06-28 16:31:45.909725

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec3fceeb76e4'
down_revision = '79df064af68d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
