"""test running migrations

Revision ID: ec990fe76c03
Revises: dc6a11ca61b5
Create Date: 2023-06-27 20:22:11.254083

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec990fe76c03'
down_revision = 'dc6a11ca61b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
