"""test running migrations

Revision ID: ed38198aeb4c
Revises: 4699e77e1735
Create Date: 2023-06-27 20:18:51.742957

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed38198aeb4c'
down_revision = '4699e77e1735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
