"""test running migrations

Revision ID: ed5420639925
Revises: 01c5004aef02
Create Date: 2023-06-28 18:10:26.278701

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed5420639925'
down_revision = '01c5004aef02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
