"""test running migrations

Revision ID: f0891cc695a0
Revises: 6ad8847014b6
Create Date: 2023-06-27 20:30:59.212667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0891cc695a0'
down_revision = '6ad8847014b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
