"""test running migrations

Revision ID: f252b81255b1
Revises: eb571c10a4d3
Create Date: 2023-06-28 18:28:31.323457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f252b81255b1'
down_revision = 'eb571c10a4d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
