"""test running migrations

Revision ID: f2ed85abce84
Revises: 5fbe75c2f725
Create Date: 2023-06-28 18:06:49.352720

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f2ed85abce84'
down_revision = '5fbe75c2f725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
