"""test running migrations

Revision ID: f4874c3d9755
Revises: 7821af94eddc
Create Date: 2023-06-28 16:29:19.999057

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f4874c3d9755'
down_revision = '7821af94eddc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
