"""test running migrations

Revision ID: f56c6267b9db
Revises: a0d31f94b675
Create Date: 2023-06-27 20:49:26.824113

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f56c6267b9db'
down_revision = 'a0d31f94b675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
