"""test running migrations

Revision ID: f6130d15976f
Revises: c357ee2ffee4
Create Date: 2023-06-28 18:02:05.159001

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f6130d15976f'
down_revision = 'c357ee2ffee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
