"""test running migrations

Revision ID: f7ba4da908f7
Revises: 2a746e1dde88
Create Date: 2023-06-28 13:19:29.883489

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f7ba4da908f7'
down_revision = '2a746e1dde88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
