"""test running migrations

Revision ID: f83026cf151c
Revises: a35ac564f7bb
Create Date: 2023-06-28 13:35:51.098456

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f83026cf151c'
down_revision = 'a35ac564f7bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
