"""test running migrations

Revision ID: f8fd92952bfa
Revises: 222af2db5d14
Create Date: 2023-06-28 16:48:03.976589

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8fd92952bfa'
down_revision = '222af2db5d14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
