"""test running migrations

Revision ID: f9c49d2c8fd8
Revises: b058958673f7
Create Date: 2023-06-28 13:39:54.678856

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f9c49d2c8fd8'
down_revision = 'b058958673f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
