"""test running migrations

Revision ID: fa0d8ebae33b
Revises: b5aeba911a95
Create Date: 2023-06-28 16:10:43.823205

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fa0d8ebae33b'
down_revision = 'b5aeba911a95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
