"""test running migrations

Revision ID: fb518b3b03c5
Revises: e409675a11f8
Create Date: 2023-06-28 13:20:55.970808

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fb518b3b03c5'
down_revision = 'e409675a11f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
