"""test running migrations

Revision ID: fc17514c8d0b
Revises: 5a6a1a7f1f30
Create Date: 2023-06-28 14:26:53.845542

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc17514c8d0b'
down_revision = '5a6a1a7f1f30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
