"""test running migrations

Revision ID: fd6fb23d2b54
Revises: cdb1b06b8d15
Create Date: 2023-06-28 18:04:09.190106

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fd6fb23d2b54'
down_revision = 'cdb1b06b8d15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
