"""test running migrations

Revision ID: ff00b468fa21
Revises: c598d963f55c
Create Date: 2023-06-28 16:28:02.822735

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff00b468fa21'
down_revision = 'c598d963f55c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
