"""test running migrations

Revision ID: ff8a8e906d43
Revises: 409ae9ed1a36
Create Date: 2023-06-28 13:46:35.878305

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff8a8e906d43'
down_revision = '409ae9ed1a36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
