"""test running migrations

Revision ID: 01ee1d016c81
Revises: fcdd9c40dc48
Create Date: 2023-06-28 16:05:14.831207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ee1d016c81'
down_revision = 'fcdd9c40dc48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
