"""test running migrations

Revision ID: 030b57c8ef98
Revises: 611cc718759a
Create Date: 2023-06-27 20:46:37.937755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030b57c8ef98'
down_revision = '611cc718759a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
