"""test running migrations

Revision ID: 141cd40c6a7f
Revises: 01ee1d016c81
Create Date: 2023-06-28 16:05:49.047631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141cd40c6a7f'
down_revision = '01ee1d016c81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
