"""test running migrations

Revision ID: 14b85cdbf002
Revises: 16f22a433920
Create Date: 2023-06-27 19:40:16.402897

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '14b85cdbf002'
down_revision = '16f22a433920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
