"""test running migrations

Revision ID: 16f22a433920
Revises: d7d49707026c
Create Date: 2023-06-27 19:39:56.208602

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '16f22a433920'
down_revision = 'd7d49707026c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
