"""test running migrations

Revision ID: 18fb6bf09886
Revises: 7dfce9c0b7ed
Create Date: 2023-06-27 19:52:00.140866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fb6bf09886'
down_revision = '7dfce9c0b7ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
