"""test running migrations

Revision ID: 230744984392
Revises: e9d1d2f29df0
Create Date: 2023-06-28 15:58:04.599454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230744984392'
down_revision = 'e9d1d2f29df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
