"""Change User's model

Revision ID: 23f115caa39a
Revises: a37e0f677d16
Create Date: 2023-06-23 10:36:29.720877

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '23f115caa39a'
down_revision = 'a37e0f677d16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
