"""test running migrations

Revision ID: 2bd9c4c652be
Revises: 7100d0ba4f6a
Create Date: 2023-06-28 16:07:16.250004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd9c4c652be'
down_revision = '7100d0ba4f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
