"""test running migrations

Revision ID: 2fd2c735171c
Revises: c5302319c20e
Create Date: 2023-06-28 15:55:40.328719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd2c735171c'
down_revision = 'c5302319c20e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
