"""test running migrations

Revision ID: 315565db553a
Revises: c57f39ec03d6
Create Date: 2023-06-28 16:02:46.983689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315565db553a'
down_revision = 'c57f39ec03d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
