"""test running migrations

Revision ID: 3912e1b3c052
Revises: cf9693fec65b
Create Date: 2023-06-27 20:13:42.924188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3912e1b3c052'
down_revision = 'cf9693fec65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
