"""test running migrations

Revision ID: 443d5610ec3c
Revises: 51b16b017435
Create Date: 2023-06-27 19:36:04.992896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '443d5610ec3c'
down_revision = '51b16b017435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
