"""test running migrations

Revision ID: 46b48b344ea4
Revises: da9d740741e1
Create Date: 2023-06-27 19:45:13.578010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '46b48b344ea4'
down_revision = 'da9d740741e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
