"""test running migrations

Revision ID: 4771a1388e61
Revises: 14b85cdbf002
Create Date: 2023-06-27 19:42:01.161805

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4771a1388e61'
down_revision = '14b85cdbf002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
