"""test running migrations

Revision ID: 47b1af3a7e37
Revises: 483e643e3041
Create Date: 2023-06-28 16:10:05.754315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b1af3a7e37'
down_revision = '483e643e3041'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
