"""test running migrations

Revision ID: 483e643e3041
Revises: 64330c99d344
Create Date: 2023-06-28 16:09:52.283381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483e643e3041'
down_revision = '64330c99d344'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
