"""test running migrations

Revision ID: 51b16b017435
Revises: 76fc66240334
Create Date: 2023-06-27 18:27:17.503942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '51b16b017435'
down_revision = '76fc66240334'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
