"""test running migrations

Revision ID: 611cc718759a
Revises: 615d9ccd2338
Create Date: 2023-06-27 20:44:08.656310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611cc718759a'
down_revision = '615d9ccd2338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
