"""test running migrations

Revision ID: 615d9ccd2338
Revises: 3912e1b3c052
Create Date: 2023-06-27 20:43:36.940243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615d9ccd2338'
down_revision = '3912e1b3c052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
