"""test running migrations

Revision ID: 64330c99d344
Revises: 9e5a70db89d1
Create Date: 2023-06-28 16:08:51.713875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64330c99d344'
down_revision = '9e5a70db89d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
