"""test running migrations

Revision ID: 7100d0ba4f6a
Revises: 141cd40c6a7f
Create Date: 2023-06-28 16:06:43.513337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7100d0ba4f6a'
down_revision = '141cd40c6a7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
