"""Change User's model

Revision ID: 711481889413
Revises: 903fc81c1ad8
Create Date: 2023-06-27 20:02:24.001045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711481889413'
down_revision = '903fc81c1ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
