"""test running migrations

Revision ID: 71ec965a3913
Revises: 4771a1388e61
Create Date: 2023-06-27 19:44:04.984845

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71ec965a3913'
down_revision = '4771a1388e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
