"""Change User's model

Revision ID: 734f4d1136fc
Revises: 8050c64a151f
Create Date: 2023-06-27 15:16:23.515149

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '734f4d1136fc'
down_revision = '8050c64a151f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
