"""test running migrations

Revision ID: 76fc66240334
Revises: 8011ab20bac8
Create Date: 2023-06-27 18:27:13.799050

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '76fc66240334'
down_revision = '8011ab20bac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
