"""Change User's model

Revision ID: 77a99d56c8cb
Revises: a0be42f8e7ac
Create Date: 2023-06-22 15:05:50.178644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '77a99d56c8cb'
down_revision = 'a0be42f8e7ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
