"""test running migrations

Revision ID: 7dfce9c0b7ed
Revises: bd8301516681
Create Date: 2023-06-27 19:50:04.265855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfce9c0b7ed'
down_revision = 'bd8301516681'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
