"""test running migrations

Revision ID: 8011ab20bac8
Revises: 734f4d1136fc
Create Date: 2023-06-27 18:26:30.059445

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8011ab20bac8'
down_revision = '734f4d1136fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
