"""Change User's model

Revision ID: 8050c64a151f
Revises: f11ad100ad14
Create Date: 2023-06-27 14:49:26.303291

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8050c64a151f'
down_revision = 'f11ad100ad14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
