"""test running migrations

Revision ID: 903fc81c1ad8
Revises: 18fb6bf09886
Create Date: 2023-06-27 19:52:55.625237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903fc81c1ad8'
down_revision = '18fb6bf09886'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
