"""test running migrations

Revision ID: 9637908b58e1
Revises: 71ec965a3913
Create Date: 2023-06-27 19:44:14.149103

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9637908b58e1'
down_revision = '71ec965a3913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
