"""Change User's model

Revision ID: 99aa00eaa09d
Revises: b18dbea93b09
Create Date: 2023-06-22 17:54:01.479774

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '99aa00eaa09d'
down_revision = 'b18dbea93b09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
