"""test running migrations

Revision ID: a0a0209359c1
Revises: 46b48b344ea4
Create Date: 2023-06-27 19:45:28.570850

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a0a0209359c1'
down_revision = '46b48b344ea4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
