"""Change User's model

Revision ID: a0be42f8e7ac
Revises: ec9be37ff1f7
Create Date: 2023-06-21 19:36:39.410295

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0be42f8e7ac"
down_revision = "ec9be37ff1f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Users",
        "user_id",
        existing_type=sa.UUID(),
        comment="Unique user identifier",
        existing_nullable=False,
    )
    op.alter_column(
        "Users",
        "salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Current salary",
        existing_nullable=False,
    )
    op.alter_column(
        "Users",
        "salary_increase_date",
        existing_type=sa.VARCHAR(),
        comment="Expected salary increase date:",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Users",
        "salary_increase_date",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Expected salary increase date:",
        existing_nullable=False,
    )
    op.alter_column(
        "Users",
        "salary",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Current salary",
        existing_nullable=False,
    )
    op.alter_column(
        "Users",
        "user_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Unique user identifier",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
