"""Change User's model

Revision ID: a37e0f677d16
Revises: 02c109794eb9
Create Date: 2023-06-22 19:56:57.512787

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a37e0f677d16'
down_revision = '02c109794eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
