"""Change User's model

Revision ID: b18dbea93b09
Revises: 77a99d56c8cb
Create Date: 2023-06-22 17:53:45.075138

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b18dbea93b09'
down_revision = '77a99d56c8cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
