"""test running migrations

Revision ID: bd8301516681
Revises: a0a0209359c1
Create Date: 2023-06-27 19:45:52.799968

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd8301516681'
down_revision = 'a0a0209359c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
