"""test running migrations

Revision ID: c5302319c20e
Revises: 030b57c8ef98
Create Date: 2023-06-28 15:55:23.622428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5302319c20e'
down_revision = '030b57c8ef98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
