"""test running migrations

Revision ID: cf9693fec65b
Revises: 7e30642d41fb
Create Date: 2023-06-27 20:12:34.526476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9693fec65b'
down_revision = '7e30642d41fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
