"""test running migrations

Revision ID: d7d49707026c
Revises: 443d5610ec3c
Create Date: 2023-06-27 19:36:32.617791

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7d49707026c'
down_revision = '443d5610ec3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
