"""test running migrations

Revision ID: da9d740741e1
Revises: 9637908b58e1
Create Date: 2023-06-27 19:44:53.762576

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da9d740741e1'
down_revision = '9637908b58e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
