"""test running migrations

Revision ID: e9d1d2f29df0
Revises: 2fd2c735171c
Create Date: 2023-06-28 15:57:49.857050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d1d2f29df0'
down_revision = '2fd2c735171c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
