"""Change User's model

Revision ID: ec9be37ff1f7
Revises: 71a7f983bd00
Create Date: 2023-06-21 17:37:48.210558

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec9be37ff1f7"
down_revision = "71a7f983bd00"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users", sa.Column("salary_increase_date", sa.String(), nullable=False)
    )
    op.drop_column("Users", "next_salary_up")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users",
        sa.Column("next_salary_up", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("Users", "salary_increase_date")
    # ### end Alembic commands ###
