"""Change User's model

Revision ID: f11ad100ad14
Revises: 23f115caa39a
Create Date: 2023-06-23 13:35:23.752288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f11ad100ad14'
down_revision = '23f115caa39a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
