"""test running migrations

Revision ID: fcdd9c40dc48
Revises: 315565db553a
Create Date: 2023-06-28 16:04:13.552323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdd9c40dc48'
down_revision = '315565db553a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
